### ISSUE TITLE
Wrong cursor position in TextInput

### ISSUE THREAD

**Issue by DaraJKong** [iced-rs/iced#2195] opened 2024-01-11 06:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Sometimes, the cursor position inside of a TextInput is offset from the "real" cursor such that characters are inserted at the wrong place. When clicking on the empty space after the TextInput's value, the cursor appears one character away from the end instead of being at the very end.

Selecting all the text inside of the input and typing some new text removes the issue.

https://github.com/iced-rs/iced/assets/32781636/2c63bb9b-6ed9-48fb-a64b-b36ed0ae8df7

It seems to be a visual bug, because typed characters are inserted correctly. However, the cursor is not displayed at the right position.

This issue happened to me several times when using the master branch of Iced in my projects. The crates.io version doesn't have that bug.

To pinpoint exactly what's causing the issue, I tried making an [SSCCE](http://sscce.org/):
https://github.com/iced-rs/iced/compare/master...DaraJKong:iced:fix/wrong_text_input_cursor_position
However, it turned out so short that it's almost an Hello World for the TextInput widget.

### What is the expected behavior?

Characters should be inserted at the cursor, not offset from it.

### Version

master

### Operating System

Linux

**Comment by hecrj** [comment] 2024-01-11 06:47
Interesting. This seems to be caused by the `fi` ligature. I'll look into it.

**Comment by hecrj** [comment] 2024-01-11 07:33
Should be fixed by #2196.

**Closed** 2024-01-11 07:45 UTC
Labels: bug, text, widget
