### ISSUE TITLE
Can't run hello world example (Linux Ubuntu 20.04)

### ISSUE THREAD

**Issue by strogiyotec** [iced-rs/iced#1173] opened 2021-12-28 02:01 UTC
Hello. I am going through the hello world example from official documentation https://docs.rs/iced/0.3.0/iced/trait.Application.html#a-simple-hello-world.
However when I try to run an executable it shows me this error 
```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Failed to unfocus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', /home/strogiyotec/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/event_processor.rs:945:30
```
Do you know how to fix it ? I am using iced `0.3` , rust version is `rustc 1.57.0` cargo `cargo 1.57.0`

**Comment by 13r0ck** [comment] 2021-12-28 07:10
> MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Looks like the issue is from your mesa driver. Mesa is the open source graphics driver for ubuntu and its derivatives. It seems like the issue is not iced related. I would start with the suggested action in the error `sysctl dev.i915.perf_stream_paranoid=0`

**Comment by tmdh** [comment] 2022-01-01 13:45
> MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

The issue is not from mesa driver. This is a common warning in Intel graphics laptops.

**Comment by hecrj** [comment] 2022-01-09 05:43
Could you try running [the `wgpu` examples](https://github.com/gfx-rs/wgpu)? If the issue is present there, then we should report it.

In any case, using the `glow` renderer by enabling the `iced_glow` feature may help.

**Comment by hecrj** [comment] 2022-01-22 08:00
- Is the issue present in all of the examples? For instance, try `game_of_life` which should choose your high performance GPU.
- Is the issue present in [the `wgpu` examples]? If yes, then please report the issue there!

Closing this for now, as it seems like a hardware compatibility issue. Feel free to reopen if there is further evidence that something is wrong with `iced` itself.

[the `wgpu` examples]: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples

**Closed by hecrj** 2022-01-22 08:00 UTC
Labels: bug
