### ISSUE TITLE
Callable pane_grid State insert methods

### ISSUE THREAD

**Issue by cryptoquick** [iced-rs/iced#656] opened 2020-12-10 19:43 UTC
How might a pane_grid be made with multiple panes already without needing to call a split method that requires a pane that comes from itself? I've tried following this logic around, but I can't seem to find a way to render a set number of panes in either a new or view method, without requiring update message interactivity of some sort that requires a pane to already exist when calling PaneGrid::new(). It might make sense to be able to instantiate a pane_grid::State<T> with configuration provided here:

https://docs.rs/iced_native/0.3.0/iced_native/widget/pane_grid/enum.Configuration.html

As far as I can tell, the state configuration enum members required do not yet exist, nor is there a way to insert into the HashMap itself in a way that makes sense to me.

Would it be sensible to do the required inserts when the pane_grid State HashMap is first instantiated? Or would it make more sense for it to be an additional method on the State that can be called multiple times? I'm not sure where it would make sense call this method, perhaps in a new or update method in a parent component, or root Application/Sandbox component.

I do see a problem might arise is that a PaneGrid can only be made from only one instance of a Pane, when this information may be known only in state when, for example, a pane grid is to be hydrated and dehydrated when persistence is desired.

**Comment by hecrj** [comment] 2020-12-10 20:24
>  It might make sense to be able to instantiate a pane_grid::State with configuration provided here

Is [`State::with_configuration`](https://docs.rs/iced_native/0.3.0/iced_native/widget/pane_grid/struct.State.html#method.with_configuration) what you are looking for?

**Comment by cryptoquick** [comment] 2020-12-10 21:21
@hecrj I don't think so? Does it allow me to set the contents of the hashmap? I see State is iterable, but I don't see an "insert", "add", or "push" method.

**Comment by hecrj** [comment] 2020-12-10 22:27
Which `HashMap`? Are you referring to the `State` internals? They are opaque. You should not need to worry about them.

A `Configuration` is generic over `T`, which should be the type that represents the state of every pane.

**Comment by cryptoquick** [comment] 2020-12-10 23:38
I agree with this, direct access to the HashMap is not ideal. The intention would be to persist things the user does and rehydrate the state of the user interface when the application is reopened.

And I don't mind splitting in the same way that the user did so. I just couldn't figure out how to do so, since the logic I'm looking at seems to loop back in on itself. It's not quite clear how I would provide a Pane to insert outside of a PaneGrid.

We're making do with a different approach for now, but myself and others may want this functionality in the future.

**Comment by twitchyliquid64** [comment] 2020-12-11 20:22
Can you do something like this?

```rust
let state = pane_grid::State::with_configuration(
  pane_grid::Configuration::Split{
    axis: pane_grid::Axis::Vertical,
    ratio: 0.5,
    a: Box::new(pane_grid::Configuration::Pane(first_pane)),
    b: Box::new(pane_grid::Configuration::Pane(second_pane)),
  });
```

Note that the type of both the panes needs to match, as this becomes the generic type. The pane_grid [example](https://github.com/hecrj/iced/blob/master/examples/pane_grid/src/main.rs) makes its own [type](https://github.com/hecrj/iced/blob/master/examples/pane_grid/src/main.rs#L188) for this: i think your only requirement there is to implement the `Widget` trait.

**Comment by jgrussell** [comment] 2021-02-25 17:27
Could anyone share a working example of initializing a pane_grid w/ multiple panes either in the PaneGrid::new() call or programmatically immediately after?  A couple of approaches are mentioned above; but, I have not been able to make either one work on my own.

Note:  I also asked this in a new [Initializing pane_grid w/ Multiple Panes](https://iced.zulipchat.com/#narrow/stream/213445-help/topic/Initializing.20pane_grid.20w.2F.20Multiple.20Panes/near/227765766) Zulip topic in the _help_ stream if that is your preferred venue.

Thank you.

**Comment by cryptoquick** [comment] 2021-02-25 17:52
I haven't resolved this issue myself, I was working on a prototype to try to do so, or in the very least, demonstrate what I want to do, but I haven't been able to get to it yet.

**Comment by hecrj** [comment] 2022-01-20 06:59
I'm gonna close this for now as it is still not clear what the issue is exactly asking for!

Feel free to reopen if you figure it out!

**Closed by hecrj** 2022-01-20 06:59 UTC
Labels: question
