### ISSUE TITLE
Incorrect font render

### ISSUE THREAD

**Issue by IohannRabeson** [iced-rs/iced#1718] opened 2023-02-18 21:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

[This font](https://www.dafont.com/tf2-build.font) is not rendered properly.
In this screenshot the 'T' is incorrect.
![image](https://user-images.githubusercontent.com/685196/219899408-8894a955-14ca-4b81-8b75-c5ead77bd27e.png)
I tried to use this font with other system and it works properly. 
I reproduce with the latest Iced, I also tried the branch 'advanced_text" but exact same result.

### What is the expected behavior?

The font render properly (here I used Inkscape to render the text as image):
![image](https://user-images.githubusercontent.com/685196/219899452-08f32515-ac48-4d52-8e96-5a95c2746642.png)

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment] 2023-02-18 21:09
Most likely a duplicate of #33. Try #1697.

**Closed by hecrj** 2023-02-18 21:09 UTC
Labels: bug
