### ISSUE TITLE
Custom widget that contains self-generated child widgets

### ISSUE THREAD

**Issue by edko99** [iced-rs/iced#709] opened 2021-01-21 17:56 UTC
I am trying to implement a widget to display an interactive list of items. I though of using `Row` widgets to layout the internal content, and to capture and respond to events. However, these row widgets will not be added by the user, but rather be generated internally by the `List` widget. Since my list can be very big, I would like to use virtual scrolling and recycle the rows. Should they be part of the List's state? Should I generate them on the fly when `layout` is called? What should I do if the user resizes the window and I need to add more rows? Is there an example I can use for inspiration?

**Comment by 13r0ck** [comment] 2021-01-21 19:45
`What should I do if the user resizes the window and I need to add more rows?`
I am not sure about the first part of your question, but maybe for the later wrap it in a pane grid then use the resize event?
https://docs.rs/iced/0.2.0/iced/widget/pane_grid/struct.ResizeEvent.html

**Comment by hecrj** [comment] 2022-01-20 07:38
Duplicate of #160. Feel free to tell us more about your use case there for further discussion!

**Closed by hecrj** 2022-01-20 07:38 UTC
Labels: question
