### ISSUE TITLE
"close" simply closes the window and does not stop the program

### ISSUE THREAD

**Issue by sgj123456** [iced-rs/iced#2495] opened 2024-07-06 09:04 UTC
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [x] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I pulled the latest iced version, and ran the example, everything worked fine. However, when I create a new project, specify the same version, and copy the sample code, the program starts normally, but when I close the program, the window is only closed, and the command line is still running. I didn't cancel any of the default features.

### What is the expected behavior?

When the window closes, the command line stops running

### Version

master

### Operating System

Linux

**Comment by sgj123456** [comment] 2024-07-06 09:08
To be clear, I didn't set any flag to prevent the program from exiting, and the same code would close normally when running in the example.

**Comment by hecrj** [comment] 2024-07-07 02:20
Are you using a `daemon`?

**Comment by sgj123456** [comment] 2024-07-07 05:27
> Are you using a `daemon`?

No, I just use Cargo run

**Comment by sgj123456** [comment] 2024-07-07 05:37
> Are you using a `daemon`?

I'm using the same ICED version with the same terminal environment, but "cargo run --package exit" always closes normally, while copying the same code and running it independently doesn't. I'm very confused about this.

**Comment by sgj123456** [comment] 2024-07-07 05:43
> Are you using a `daemon`?

Even if I use path to specify the repository that is cloned to the local and leave the default features, this problem persists. Running "cargo run --package...", to the repository of the iced, everything works fine.

**Comment by hecrj** [comment] 2024-07-07 23:43
I am closing this since it's very likely either user error or an environment issue.

If you can't figure it out, please share both your `Cargo.toml` and the `main.rs` file that reproduce the issue. Even if you copied the code and pointed to the same version, share an actual crate that _directly_ reproduces the issue so we can discard user error.

**Closed by hecrj** 2024-07-07 23:43 UTC
Labels: bug

**Comment by sgj123456** [comment] 2024-07-08 03:24
> I am closing this since it's very likely either user error or an environment issue.
> 
> If you can't figure it out, please share both your `Cargo.toml` and the `main.rs` file that reproduce the issue. Even if you copied the code and pointed to the same version, share an actual binary crate that _directly_ reproduces the issue so we can discard user error.

Here's my demo.
https://github.com/sgj123456/iced_t

**Comment by sgj123456** [comment] 2024-07-08 03:40
> I am closing this since it's very likely either user error or an environment issue.
> 
> If you can't figure it out, please share both your `Cargo.toml` and the `main.rs` file that reproduce the issue. Even if you copied the code and pointed to the same version, share an actual binary crate that _directly_ reproduces the issue so we can discard user error.

It's worth mentioning that I had this issue with the Hyprland desktop, but when I switched the environment to gnome, everything worked fine

**Comment by sgj123456** [comment] 2024-07-08 17:34
> I am closing this since it's very likely either user error or an environment issue.
> 
> If you can't figure it out, please share both your `Cargo.toml` and the `main.rs` file that reproduce the issue. Even if you copied the code and pointed to the same version, share an actual binary crate that _directly_ reproduces the issue so we can discard user error.

cosmic same Hyprland

**Comment by hecrj** [comment] 2024-07-08 22:35
Did you try `cargo update`?

**Comment by sgj123456** [comment] 2024-07-09 03:06
> Did you try `cargo update`?

I've been trying to pass the update

**Comment by sgj123456** [comment] 2024-07-11 08:08
> Did you try `cargo update`?

After my testing, I found that on the platform in question Poll will never be in the Ready state, even if the Close_Request is successfully triggered, the specific reason I haven't figured out, hopefully this will be useful for iced.
