### ISSUE TITLE
Text not rendering correctly in the tour example.

### ISSUE THREAD

**Issue by FaisalAhmedAlghamdi** [iced-rs/iced#2132] opened 2023-11-07 14:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

![image](https://github.com/iced-rs/iced/assets/142179718/e46625f1-90b2-46e2-b5aa-24b30536d8c9)

### What is the expected behavior?

The text should not be distorted.

system info:
```
Device name	DESKTOP-EP4LQDE
Processor	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	A2B41964-60C8-49B9-B43B-78C3635331BA
Product ID	00330-80000-00000-AA231
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎6/‎2023
OS build	19045.3636
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```

```
GPU = nvidia gtx 1650 driver version 536.23
cargo 1.73.0 (9c4383fb5 2023-08-26)
MSVC v143
```
code ran from iced master repository.

### Version

crates.io release

### Operating System

Windows

**Comment by FaisalAhmedAlghamdi** [comment] 2023-11-07 14:19
issue only present in debug build

**Comment by genusistimelord** [comment] 2023-11-09 20:52
I tested this as well and yes the text bugs out when you start to resize the text output.

**Comment by hecrj** [comment] 2023-11-11 05:14
Issue is caused by a recent patch to `etagere`: https://github.com/nical/etagere/pull/27#issuecomment-1806686983

You can fix it by manually downgrading the dependency to `0.2.8`:

```
cargo update --package etagere --precise 0.2.8
```

**Comment by hecrj** [comment] 2023-11-11 22:04
The affected `etagere` version has been yanked; the issue should be fixed.

**Closed by hecrj** 2023-11-11 22:04 UTC
Labels: bug
