### ISSUE TITLE
Length::Fill fills window, not parent

### ISSUE THREAD

**Issue by zackyancey** [iced-rs/iced#304] opened 2020-04-18 18:45 UTC
I'm new to GUI programming, so I may just be going about this the wrong way, but I haven't found a way to get the results that I'm looking for. Consider the following layout:

```rust
use iced::{button, Button, Column, Element, Length, Row, Sandbox, Settings, Text};

pub fn main() {
    App::run(Settings::default())
}

#[derive(Default)]
struct App {
    button_a: button::State,
    button_b: button::State,
    button_c: button::State,
}

impl Sandbox for App {
    type Message = ();

    fn new() -> Self {
        Self::default()
    }

    fn title(&self) -> String {
        String::from("Fill parent")
    }

    fn update(&mut self, _message: ()) {}

    fn view(&mut self) -> Element<()> {
        let button_a = Button::new(&mut self.button_a, Text::new("aaa")).on_press(());
        let button_b = Button::new(&mut self.button_b, Text::new("bbbb")).on_press(());
        let button_c = Button::new(&mut self.button_c, Text::new("c")).on_press(());
        Row::new()
            .height(Length::Shrink)
            .width(Length::Shrink)
            .push(button_a.height(Length::Units(100)))
            .push(
                Column::new()
                    .width(Length::Shrink)
                    .height(Length::Fill)
                    .push(button_b.width(Length::Fill).height(Length::Fill))
                    .push(button_c.width(Length::Fill).height(Length::Fill)),
            )
            .into()
    }
}
```

I want B and C to fill their column horizontally and vertically. Since the column's width is set to shrink, the column's width should be the shortest possible (just wide enough for button B). Similarly, the column's height should fill the row, which is shrunk to the height of button A. So something like this:

![image](https://user-images.githubusercontent.com/31323996/79650544-5cb56980-816e-11ea-9436-88b3a4888c92.png)

However, instead on desktop I get this:
![image](https://user-images.githubusercontent.com/31323996/79655246-bc604480-816f-11ea-97a9-d5e82e4c0080.png)
The elements fill the entire window, not their container.

and on web:
![image](https://user-images.githubusercontent.com/31323996/79657129-47413f00-8170-11ea-99ae-1d3e1c64f63f.png)
Widths seem to work the way I hoped, but setting height doesn't seem to work at all.

I think what should be happening is that `Length::Fill` elements should only fill the space available in the parent, and `Length::Shrink` containers should take the minimum possible size for all elements and pick the largest one. If that's not the way it should work, then maybe a new variant (`Length::FillParent`?) would be useful.

**Comment by hecrj** [comment] 2020-04-18 19:06
Yes, `Shrink` should be renamed to something like `Content`.

The current native layout engine, while usable, is one of the most experimental parts of the library. As you see, `iced_web` doesn't completely match its behavior.

We need to iterate further and fix any inconsistencies like this one. Either by renaming things or improving the engine itself.

**Comment by hecrj** [comment] 2022-01-18 15:07
After #1044, I believe the behavior described in the issue is easily achievable. Closing!

**Closed by hecrj** 2022-01-18 15:07 UTC
Labels: improvement, layout

**Comment by Hurricane996** [comment] 2025-05-22 08:20
https://github.com/iced-rs/iced/commit/9e815cb749f1bf6bce0232e870be266aca0c0742 removed Alignment::Fill. Has anything replaced it?
