### ISSUE TITLE
no focus; arrow keys and tab does not work

### ISSUE THREAD

**Issue by Lukas1818** [iced-rs/iced#1130] opened 2021-11-28 16:38 UTC
I have write a very small gui with 3 buttons. I notify that I can neither use arrow keys nor tab to navigate between the buttons.
I am not sure if this a bug or a missing feature.
![image](https://user-images.githubusercontent.com/44570204/143777302-e04d0006-e817-41cf-bd45-0849074df211.png)

https://github.com/Lukas1818/rusty-vocabulary/blob/5a5c27f4cb8a161985d2f5c0b50ed50b63d40581/src/main.rs

**Comment by hecrj** [comment] 2021-11-29 07:33
This is a missing feature! Duplicate of #489.

**Closed by hecrj** 2021-11-29 07:33 UTC
