### ISSUE TITLE
Request: option to mark a Text as selectable/copyable

### ISSUE THREAD

**Issue by agraven** [iced-rs/iced#645] opened 2020-12-01 08:53 UTC
There are lots of situations where users being able to select and/or copy some text they won't need to edit is helpful. In a chat program for example, you might want to copy something someone wrote to you, or if you're displaying an error message, the user might want to copy it and look it up.

Therefore I'd like to suggest adding a `.selectable()` method to the `Text` widget which lets users select the text it displays, assuming it's feasible to do so without significantly changing the architecture of `Text`.

**Comment by yusdacra** [comment] 2020-12-01 10:31
Perhaps we can move the text selection logic and rendering from `TextEdit` to `Text`? This would need the `Text` to hold state, but we can work around this by making the state optional `Text::selectable(mut self, Option<&mut State>)`.

**Comment by twitchyliquid64** [comment] 2020-12-04 02:44
This came up on the iced chat the other day - I dont think theres any way to do this neatly, but as @yusdacra has mentioned it should be plausible with a `text_edit`, some custom styling, and by ignoring the event that gets sent through `update()` when the text_input is changed.

At a guess, you would want to make the focused style no different to the normal style + not have any borders:

```rust
pub struct TextInput;

impl text_input::StyleSheet for TextInput {
    fn active(&self) -> text_input::Style {
        text_input::Style {
            background: Background::Color(Color::BLACK),
            border_radius: 0.0,
            border_width: 0.0,
            border_color: Color::BLACK,
        }
    }

    fn focused(&self) -> text_input::Style {
        text_input::Style {
            border_color: Color::from_rgb(0.5, 0.5, 0.5),
            ..self.active()
        }
    }

    fn placeholder_color(&self) -> Color {
        Color::from_rgb(0.7, 0.7, 0.7)
    }

    fn value_color(&self) -> Color {
        Color::from_rgb(1.0, 1.0, 1.0)
    }

    fn selection_color(&self) -> Color {
        Color::from_rgb(0.0, 0.2, 0.2)
    }
}
```

As well as ignore the message you mapped for the input change event in the parent-widget/application `update()` implementation:

```rust
match message {
  Message::InputChanged(value) => {
    self.input_value = value;
    }
```

**Comment by hecrj** [comment] 2022-01-20 06:57
Duplicate of #36.

**Closed by hecrj** 2022-01-20 06:57 UTC
Labels: feature
